[package]
name = "nethsm-sdk-rs"
version = "0.1.0"
authors = ["Nitrokey <info@nitrokey.com>"]
description = "All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian. "
license = "MIT"
edition = "2018"
exclude = [
  "generator/*",
  "docs/*",
  ".openapi-generator/*",
  ".openapi-generator-ignore",
  "generator_conf.yaml",
  "update_openapi.sh",
]

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "^2.2"
uuid = { version = "^1.0", features = ["serde"] }

[dependencies.reqwest]
version = "^0.11"
features = ["json", "multipart"]
