/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 * Contact: Nitrokey <info@nitrokey.com>
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ClusterMemberAddResponse {
    #[serde(rename = "members")]
    pub members: Vec<crate::models::ClusterMember>,
    #[serde(rename = "joinerKit")]
    pub joiner_kit: String,
}

impl ClusterMemberAddResponse {
    pub fn new(
        members: Vec<crate::models::ClusterMember>,
        joiner_kit: String,
    ) -> ClusterMemberAddResponse {
        ClusterMemberAddResponse {
            members,
            joiner_kit,
        }
    }
}
