/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 * Contact: Nitrokey <info@nitrokey.com>
 * Generated by: https://openapi-generator.tech
 */

/// ClusterSnapshot : Statistics about the local cluster database snapshot. This is only present when etcd is not running.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ClusterSnapshot {
    #[serde(rename = "hash")]
    pub hash: i32,
    #[serde(rename = "revision")]
    pub revision: i32,
    #[serde(rename = "totalKey")]
    pub total_key: i32,
    #[serde(rename = "totalSize")]
    pub total_size: i32,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl ClusterSnapshot {
    /// Statistics about the local cluster database snapshot. This is only present when etcd is not running.
    pub fn new(hash: i32, revision: i32, total_key: i32, total_size: i32) -> ClusterSnapshot {
        ClusterSnapshot {
            hash,
            revision,
            total_key,
            total_size,
            version: None,
        }
    }
}
