/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 * Contact: Nitrokey <info@nitrokey.com>
 * Generated by: https://openapi-generator.tech
 */

/// ClusterLogItem : A log message from etcd on the current node. The level is warning or above.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ClusterLogItem {
    #[serde(rename = "level")]
    pub level: String,
    #[serde(rename = "msg", skip_serializing_if = "Option::is_none")]
    pub msg: Option<String>,
}

impl ClusterLogItem {
    /// A log message from etcd on the current node. The level is warning or above.
    pub fn new(level: String) -> ClusterLogItem {
        ClusterLogItem { level, msg: None }
    }
}
