/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 * Contact: Nitrokey <info@nitrokey.com>
 * Generated by: https://openapi-generator.tech
 */

/// ClusterState : Status of etcd cluster process on the local node.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ClusterState {
    /// Present when the cluster process has exited on the local node with this exit code. An exit code of 0 indicates success (e.g. the node has cleanly left the cluster).
    #[serde(rename = "exited", skip_serializing_if = "Option::is_none")]
    pub exited: Option<i32>,
    /// Present when the cluster process has been killed by this signal.
    #[serde(rename = "signaled", skip_serializing_if = "Option::is_none")]
    pub signaled: Option<i32>,
    /// Present when the cluster process has been stopped by this signal.
    #[serde(rename = "stopped", skip_serializing_if = "Option::is_none")]
    pub stopped: Option<i32>,
    /// Whether the cluster process is currently running.
    #[serde(rename = "running")]
    pub running: bool,
}

impl ClusterState {
    /// Status of etcd cluster process on the local node.
    pub fn new(running: bool) -> ClusterState {
        ClusterState {
            exited: None,
            signaled: None,
            stopped: None,
            running,
        }
    }
}
