/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 * Contact: Nitrokey <info@nitrokey.com>
 * Generated by: https://openapi-generator.tech
 */

/// HealthDiagnoseData : Information about the health of the etcd process on the current node, including the process running state, exit code, and recent logs.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct HealthDiagnoseData {
    /// A list of recent log messages from etcd on the current node.
    #[serde(rename = "clusterLogs")]
    pub cluster_logs: Vec<crate::models::ClusterLogItem>,
    #[serde(rename = "clusterSnapshot", skip_serializing_if = "Option::is_none")]
    pub cluster_snapshot: Option<Box<crate::models::ClusterSnapshot>>,
    #[serde(rename = "clusterState")]
    pub cluster_state: Box<crate::models::ClusterState>,
}

impl HealthDiagnoseData {
    /// Information about the health of the etcd process on the current node, including the process running state, exit code, and recent logs.
    pub fn new(
        cluster_logs: Vec<crate::models::ClusterLogItem>,
        cluster_state: crate::models::ClusterState,
    ) -> HealthDiagnoseData {
        HealthDiagnoseData {
            cluster_logs,
            cluster_snapshot: None,
            cluster_state: Box::new(cluster_state),
        }
    }
}
