/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 * Contact: Nitrokey <info@nitrokey.com>
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Ipv6Config {
    #[serde(rename = "cidr")]
    pub cidr: String,
    #[serde(rename = "gateway", deserialize_with = "Option::deserialize")]
    pub gateway: Option<String>,
}

impl Ipv6Config {
    pub fn new(cidr: String, gateway: Option<String>) -> Ipv6Config {
        Ipv6Config { cidr, gateway }
    }
}
