/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 * Contact: Nitrokey <info@nitrokey.com>
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct NetworkConfigOutput {
    #[serde(rename = "ipAddress")]
    pub ip_address: String,
    #[serde(rename = "netmask")]
    pub netmask: String,
    #[serde(rename = "gateway")]
    pub gateway: String,
    #[serde(rename = "ipv6", skip_serializing_if = "Option::is_none")]
    pub ipv6: Option<Box<crate::models::Ipv6Config>>,
}

impl NetworkConfigOutput {
    pub fn new(ip_address: String, netmask: String, gateway: String) -> NetworkConfigOutput {
        NetworkConfigOutput {
            ip_address,
            netmask,
            gateway,
            ipv6: None,
        }
    }
}
