/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 * Contact: Nitrokey <info@nitrokey.com>
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[non_exhaustive]
pub struct NtpConfig {
    /// IP address (v4 or v6) of the NTP server. If absent, means NTP is not configured.
    #[serde(rename = "ntpIP", skip_serializing_if = "Option::is_none")]
    pub ntp_ip: Option<String>,
    /// Hostname of the NTS server (enables Network Time Security). If absent, means NTS is not configured.
    #[serde(rename = "ntsName", skip_serializing_if = "Option::is_none")]
    pub nts_name: Option<String>,
}

impl NtpConfig {
    pub fn new() -> NtpConfig {
        NtpConfig {
            ntp_ip: None,
            nts_name: None,
        }
    }
}
